# Generated by Django 2.0 on 2020-01-23 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='icon',
            field=models.ImageField(default='/media/uploads/article/2020/01/22/TIM图片20191102092926_NfOKn2D.jpg', upload_to='uploads/%Y/%m/%d'),
        ),
    ]
